import {
  StyleSheet,
  Dimensions,
} from 'react-native'

let width=Dimensions.get('window').width
let height=Dimensions.get('window').height

export default StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'#f5FcFF'
    },
    header:{
      flexDirection:'row',
      justifyContent:'center',
      alignItems:'center',
      width:width,
      height:60,
      paddingHorizontal:10,
      borderBottomWidth:1,
      borderColor:'rgba(0,0,0,0.1)',
      backgroundColor:'#ee735c'
    },
    backBox:{
      position:'absolute',
      left:14,
      top:18,
      width:50,
      flexDirection:'row',
      alignItems:'center'
    },
    headerTitle:{
      // width:width-120,
      color:'#fff',
      textAlign:'center',
      fontSize:18,
      fontWeight:'600'
    },
    backIcon:{
      color:'#fff',
      fontSize:20,
      marginRight:5
    },
    backText:{
      color:'#fff'
    },

    videoBox:{
      alignItems:'center',
      width:width,
      height:width*0.56+2,
      backgroundColor:'#000'
    },
    video:{
      width:width,
      height:width*0.56,
      backgroundColor:'#000'
    },
    failText:{
      position:'absolute',
      left:0,
      top:90,
      width:width,
      textAlign:'center',
      color:'#fff',
      backgroundColor:'transparent'
    },
    loading:{
      position:'absolute',
      left:0,
      top:80,
      width:width,
      alignSelf:'center',
      backgroundColor:'transparent'
    },
    progressBox:{
      width:width,
      height:2,
      backgroundColor:'#eee'
    },
    progressBar:{
      width:0,
      height:2,
      backgroundColor:'#F75353'
    },

    playIcon:{
      position:'absolute',
      top:90,
      left:width/2-30,
      width:60,
      height:60,
      paddingTop:8,
      paddingLeft:20,
      backgroundColor:'transparent',
      borderColor:'#fff',
      borderWidth:1,
      borderRadius:30,
      color:'#ed7b66'
    },

    pauseBtn:{
      position:'absolute',
      left:0,
      top:0,
      width:width,
      height:width*0.56,
    },
    resumeIcon:{
      position:'absolute',
      top:80,
      left:width/2-30,
      width:60,
      height:60,
      paddingTop:8,
      paddingLeft:20,
      backgroundColor:'transparent',
      borderColor:'#fff',
      borderWidth:1,
      borderRadius:30,
      color:'#ed7b66'
    },

    infoBox:{
      width:width,
      flexDirection:'row',
      justifyContent:'center',
      marginTop:10,
    },
    avatar:{
      width:60,
      height:60,
      marginRight:10,
      marginLeft:10,
      borderRadius:30
    },
    descBox:{
      flex:1
    },
    nickname:{
      fontSize:18,
    },
    title:{
      marginTop:8,
      fontSize:16,
      color:'#666'
    },
    replyBox:{
      flexDirection:'row',
      justifyContent:'flex-start',
      marginTop:10
    },
    replyAvatar:{
      width:40,
      height:40,
      marginHorizontal:10,
      borderRadius:20,
    },
    replyNickname:{
      color:'#666'
    },
    replyContent:{
      color:'#666',
      marginTop:4
    },
    reply:{
      flex:1
    },
    loadingMore:{
      marginVertical:20,
    },
    loadingText:{
      color:'#ccc',
      textAlign:'center'
    },
    listHeader:{
      marginTop:10,
      width:width
    },
    modalContainer:{
      flex:1,
      paddingTop:10,
      backgroundColor:'#fff',
      flexDirection:'column',
      alignItems:'center'
    },
    closeIcon:{
      color:'#fff',
      fontSize:20,
      marginRight:5
    },
    modalHeader:{
      paddingLeft:10,
      paddingTop:16,
      paddingBottom:10,
      backgroundColor:'#ee735c',
      flexDirection:'row'
    },
    commentBox:{
      marginVertical:10,
      padding:4,
      width:width,
    },
    comment:{
      flexDirection:'column'
    },
    commentText:{
      marginBottom:10,
      fontSize:18,
      fontWeight:'600'
    },
    submitBtn:{
      width:width-20,
      padding:10,
      marginVertical:16,
      borderWidth:1,
      borderColor:'#ee735c',
      backgroundColor:'#ee735c',
      borderRadius:4,
      color:'#fff',
      fontSize:18,
      fontWeight:'600'
    },
    contentText:{
      height:60,
      padding:6,
      width:width-20,
      borderWidth:1,
      borderColor:'#eee',
      borderRadius:4,
      color:'#ccc',
      fontSize:16,
      marginLeft:6,
      marginBottom:6
    },
    
    content:{
      paddingHorizontal:8,
      paddingTop:8,
      color:'#333',
      borderWidth:1,
      borderColor:'#ddd',
      borderRadius:4,
      fontSize:14
    },
    commentArea:{
      width:width,
      marginTop:6,
      paddingHorizontal:10,
      paddingBottom:6,
      borderBottomWidth:1,
      borderBottomColor:'#ccc'
    },
    commentTitle:{
      color:'#4C4B4B',
      padding:6
    }
})

