import {
  StyleSheet,
  Dimensions,
} from 'react-native'

let width=Dimensions.get('window').width


export default StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'#eee'
    },
    toolBar:{
      flexDirection:'row',
      paddingTop:16,
      paddingBottom:10,
      backgroundColor:'#ee735c'
    },
    toolbarTitle:{
      flex:1,
      fontSize:16,
      color:'#fff',
      textAlign:'center',
      fontWeight:'600'
    },
    toolbarExtra:{
      position:'absolute',
      width:60,
      height:30,
      right:10,
      top:20,
      color:'#fff',
      textAlign:'right',
      fontWeight:'600',
      fontSize:14
    },
    avatarContainer:{
      width:width,
      height:140,
      alignItems:'center',
      justifyContent:'center',
      backgroundColor:'#ccc'
    },
    avatarTip:{
      color:'#fff',
      backgroundColor:'transparent',
      fontSize:14
    },
    avatarBox:{
      marginTop:16,
      alignItems:'center',
      justifyContent:'center'
    },
    avatar:{
      marginBottom:15,
      width:width*0.2,
      height:width*0.2,
      resizeMode:'cover',
      borderRadius:width*0.5
    },
    plusIcon:{
      padding:20,
      paddingHorizontal:26,
      color:'#999',
      fontSize:24,
      backgroundColor:'#fff',
      borderRadius:8
    },
    userInfoBox:{
      flexDirection:'column',
      width:width
    },
    userInfoItem:{
      width:width,
      padding:10,
      height:50,
      flexDirection:'row',
      justifyContent:'space-between',
      borderBottomWidth:1,
      borderColor:'#E6E3E3',
      backgroundColor:'#fff'
    },
    userInfoText_a:{
      fontSize:18,
      color:'#333'
    },
    userInfoText_b:{
      fontSize:16,
      color:'#888'
    },
    modalContainer:{
      flex:1,
      backgroundColor:'#eee'
    },
    modalHeader:{
      paddingLeft:10,
      paddingTop:16,
      paddingBottom:10,
      backgroundColor:'#ee735c',
      flexDirection:'row'
    },
    fieldItem:{
      flexDirection:'row',
      alignItems:'center',
      height:50,
      paddingHorizontal:16,
      borderColor:'#eee',
      borderBottomWidth:1,
      backgroundColor:'#fff'
    },
    label:{
      color:'#333',
      marginRight:10,
      width:60
    },
    gender:{
      backgroundColor:'#ccc',
    },
    genderChecked:{
      backgroundColor:'#ee735c'
    },
    inputField:{
      height:50,
      flex:1,
      color:'#666',
      fontSize:14,
      paddingTop:12
    },
    fieldItemNote:{
      flexDirection:'row',
      justifyContent:'space-between',
      height:80,
      paddingHorizontal:16,
      paddingTop:12,
      borderColor:'#eee',
      borderBottomWidth:1,
      backgroundColor:'#fff'
    },
    inputFieldNote:{
      height:80,
      flex:1,
      color:'#666',
      fontSize:14,
      marginTop:-26,
    },
    closeIcon:{
      color:'#fff',
      fontSize:20,
      marginRight:5
    },
    backText:{
      color:'#fff'
    },
    btn:{
      marginHorizontal:10,
      padding:10,
      marginTop:20,
      backgroundColor:'#ee735c',
      borderColor:'#ee735c',
      borderWidth:1,
      borderRadius:4,
      color:'#fff'
    }
})
