import {
  StyleSheet,
  Dimensions,
} from 'react-native'

let width=Dimensions.get('window').width
let height=Dimensions.get('window').height

export default StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'#fff'
    },
    toolBar:{
      flexDirection:'row',
      paddingTop:16,
      paddingBottom:10,
      backgroundColor:'#ee735c'
    },
    toolbarTitle:{
      flex:1,
      fontSize:16,
      color:'#fff',
      textAlign:'center',
      fontWeight:'600'
    },
    toolbarExtra:{
      position:'absolute',
      right:10,
      top:20,
      color:'#fff',
      textAlign:'right',
      fontWeight:'600',
      fontSize:14
    },
    page:{
      flex:1,
      alignItems:'center'
    },
    uploadContainer:{
      marginTop:height*0.2,
      width:width-40,
      paddingBottom:10,
      borderWidth:1,
      borderColor:'#eee',
      justifyContent:'center',
      borderRadius:6,
      backgroundColor:'#fff'
    },
    uploadTitle:{
      textAlign:'center',
      fontSize:16,
      marginBottom:10,
      color:'#333'
    },
    uploadDesc:{
      color:'#999',
      textAlign:'center',
      fontSize:12
    },
    uploadIcon:{
      fontSize:100
    },
    uploadBox:{
      flex:1,
      flexDirection:'column',
      justifyContent:'center',
      alignItems:'center'
    },

    videoContainer:{
      width:width,
      justifyContent:'center',
      alignItems:'flex-start',
    },
    videoBox:{
      width:width,
      height:height*0.6,
      backgroundColor:'#333'
    },
    video:{
      width:width,
      height:height*0.6,
      backgroundColor:'#333'
    },
    progressTipBox:{
      position:'absolute',
      left:0,
      bottom:0,
      width:width,
      height:30,
      backgroundColor:'rgba(244,244,244,0.65)'
    },
    progressTip:{
      color:'#333',
      width:width-10,
      padding:5
    },
    progressBar:{
      width:width
    },
    recordBox:{
      width:width,
      height:60,
      alignItems:'center'
    },
    recordIconBox:{
      width:68,
      height:68,
      marginTop:-30,
      borderRadius:34,
      borderWidth:1,
      borderColor:'transparent',
      backgroundColor:'#ee735c',
      alignItems:'center',
      justifyContent:'center'
    },
    recordIcon:{
      fontSize:58,
      backgroundColor:'transparent',
      color:'#fff'
    },
    countBtn:{
      fontSize:32,
      fontWeight:'600',
      color:'#fff'
    },
    recordOn:{
      backgroundColor:'#ccc'
    },
    previewIcon:{
      marginRight:5,
      fontSize:20,
      color:'#fff',
      backgroundColor:'transparent'
    },
    uploadAudioBox:{
      // width:width,
      // height:60,
      // alignItems:'center',
      // justifyContent:'center'
    },
    uploadAudioText:{
      width:width,
      height:60,
      alignItems:'center',
      flex:1,
      flexDirection:'row',
      justifyContent:'space-between',
      padding:6,
    },
    previewText:{
      fontSize:18,
      color:'#fff',
      backgroundColor:'transparent'
    },
    previewBox:{
      width:130,
      borderRadius:4,
      paddingVertical:6,
      backgroundColor:'#ee735c',
      borderColor:'#ee735c',
      flexDirection:'row',
      justifyContent:'center',
      alignItems:'center'
    },

    modalContainer:{
      flex:1,
      width:width,
      height:height,
      backgroundColor:'#fff'
    },
    modalHeader:{
      paddingLeft:10,
      paddingTop:16,
      paddingBottom:10,
      backgroundColor:'#ee735c',
      flexDirection:'row'
    },
    inputField:{
      height:36,
      textAlign:'center',
      color:'#666',
      fontSize:14
    },
    closeIcon:{
      color:'#fff',
      fontSize:20,
      marginRight:5
    },
    submitBox:{
      marginTop:50,
      padding:15
    },
    btn:{
      marginHorizontal:10,
      padding:10,
      backgroundColor:'#ee735c',
      borderColor:'#ee735c',
      borderWidth:1,
      borderRadius:4,
      color:'#fff'
    },
    disabledBtn:{
      marginHorizontal:10,
      padding:10,
      backgroundColor:'#F7A495',
      borderColor:'#F7A495',
      borderWidth:1,
      borderRadius:4,
      color:'#ECEAE9'
    },
    loadingText:{
      marginBottom:10,
      textAlign:'center',
      color:'#ee735c'
    },
    loadingBox:{
      width:width,
      height:50,
      marginTop:30,
      padding:15,
      alignItems:'center'
    },
    filedBox:{
      width:width-40,
      height:36,
      marginHorizontal:20,
      marginTop:30,
      borderBottomWidth:1,
      borderBottomColor:'#eaeaea'
    },
    loadingAnimationModal:{
      height:height,
      width:width,
      flexDirection:'column',
      backgroundColor:'#f5FcFF',
      alignItems:'center',
      paddingTop:height*0.28
    },
    loadingModalText:{
      fontSize:20,
      color:'#ee735c',
      fontWeight:'600',
      marginBottom:18
    }
})

